version: '0.1'
services:
  express:
    image: node
    ports:
      - 8000:8000
    environment:
      PORT: 8000
    build:
      context: ./
      target: dev
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules